/**
 * Generates Angular environment files from .env or CI environment variables.
 * Run automatically via `prestart` and `prebuild` npm hooks.
 *
 * Local dev:   create frontend/.env (gitignored), then `npm start`
 * CI / deploy: set SUPABASE_URL and SUPABASE_ANON_KEY as environment variables
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Parse .env file (if present)
const dotenv = {};
try {
  const lines = readFileSync(join(__dirname, '.env'), 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq > 0) {
      dotenv[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
    }
  }
} catch {
  // .env not found — fall through to process.env
}

// process.env takes priority over .env (allows CI to override)
const url = process.env['SUPABASE_URL'] ?? dotenv['SUPABASE_URL'] ?? '';
const key = process.env['SUPABASE_ANON_KEY'] ?? dotenv['SUPABASE_ANON_KEY'] ?? '';

if (!url || !key) {
  console.warn('⚠ SUPABASE_URL or SUPABASE_ANON_KEY is not set. Create frontend/.env from .env.example');
}

const envDir = join(__dirname, 'src/environments');

writeFileSync(
  join(envDir, 'environment.ts'),
  `// Auto-generated by set-env.mjs — do not commit\nexport const environment = {\n  production: false,\n  supabaseUrl: '${url}',\n  supabaseAnonKey: '${key}',\n};\n`,
);

writeFileSync(
  join(envDir, 'environment.prod.ts'),
  `// Auto-generated by set-env.mjs — do not commit\nexport const environment = {\n  production: true,\n  supabaseUrl: '${url}',\n  supabaseAnonKey: '${key}',\n};\n`,
);

console.log('✔ environment.ts and environment.prod.ts generated');
